name: Deploy JavaDoc

on:
  push:
    branches:
      - "main"
    paths:
      - "**/src/main/**.kt"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin" # aka adopt

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run build
        run: ./gradlew dokkaHtmlMultiModule -Pandroid.experimental.settings.executionProfile=ci
        env:
          GPR_USERNAME: ${{ github.repository_owner }}
          GPR_TOKEN: ${{ github.token }}

      - uses: actions/upload-artifact@v4
        with:
          name: javadoc-html
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Prepare Repository
        run: |
          rm -rf *
          rm -rf .github .idea .gitignore .chglog
          git checkout --orphan static-feature/pages

      - uses: actions/download-artifact@v4
        with:
          name: javadoc-html

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          push: origin static-feature/pages --force
          message: 'Documentation'
